# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'rest-client', '~> 2.1' #Se especifica la gema y la version a usar
